# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Elektronik/FPGA/NeTV2/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_bram_if_cntlr_0/MB_NoCache_MIG_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'MB_NoCache_MIG_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Elektronik/FPGA/NeTV2/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_bram_if_cntlr_0/MB_NoCache_MIG_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_NoCache_MIG_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Elektronik/FPGA/NeTV2/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_bram_if_cntlr_0/MB_NoCache_MIG_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'MB_NoCache_MIG_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Elektronik/FPGA/NeTV2/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_bram_if_cntlr_0/MB_NoCache_MIG_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_NoCache_MIG_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
