set_property PACKAGE_PIN J19 [get_ports Clk50M]
set_property IOSTANDARD LVCMOS33 [get_ports Clk50M]
create_clock -period 20.000 -name Clk50M [get_ports Clk50M]

set_property PACKAGE_PIN M21 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property PACKAGE_PIN N20 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property PACKAGE_PIN L21 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property PACKAGE_PIN AA21 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property PACKAGE_PIN R19 [get_ports LED4]
set_property IOSTANDARD LVCMOS33 [get_ports LED4]
set_property PACKAGE_PIN M16 [get_ports LED5]
set_property IOSTANDARD LVCMOS33 [get_ports LED5]

#set_property PACKAGE_PIN B17 [get_ports HAX7]
#set_property IOSTANDARD LVCMOS33 [get_ports HAX7]
#set_property PACKAGE_PIN A18 [get_ports HAX8]
#set_property IOSTANDARD LVCMOS33 [get_ports HAX8]

set_property PACKAGE_PIN E14 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN E13 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
