# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project_2/NeTV2.xdc

# Block Designs: bd/MB_NoCache_MIG/MB_NoCache_MIG.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG || ORIG_REF_NAME==MB_NoCache_MIG} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_clk_wiz_0_0/MB_NoCache_MIG_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_clk_wiz_0_0 || ORIG_REF_NAME==MB_NoCache_MIG_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_xlconstant_0_0/MB_NoCache_MIG_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_xlconstant_0_0 || ORIG_REF_NAME==MB_NoCache_MIG_xlconstant_0_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_xlconstant_0_1/MB_NoCache_MIG_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_xlconstant_0_1 || ORIG_REF_NAME==MB_NoCache_MIG_xlconstant_0_1} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_mig_7series_0_1/MB_NoCache_MIG_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_mig_7series_0_1 || ORIG_REF_NAME==MB_NoCache_MIG_mig_7series_0_1} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_axi_uartlite_0_0/MB_NoCache_MIG_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_axi_uartlite_0_0 || ORIG_REF_NAME==MB_NoCache_MIG_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_0/MB_NoCache_MIG_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_microblaze_0_0 || ORIG_REF_NAME==MB_NoCache_MIG_microblaze_0_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_v10_0/MB_NoCache_MIG_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_dlmb_v10_0 || ORIG_REF_NAME==MB_NoCache_MIG_dlmb_v10_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_ilmb_v10_0/MB_NoCache_MIG_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_ilmb_v10_0 || ORIG_REF_NAME==MB_NoCache_MIG_ilmb_v10_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_bram_if_cntlr_0/MB_NoCache_MIG_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_NoCache_MIG_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_ilmb_bram_if_cntlr_0/MB_NoCache_MIG_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_NoCache_MIG_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_lmb_bram_0/MB_NoCache_MIG_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_lmb_bram_0 || ORIG_REF_NAME==MB_NoCache_MIG_lmb_bram_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_xbar_0/MB_NoCache_MIG_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_xbar_0 || ORIG_REF_NAME==MB_NoCache_MIG_xbar_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_3/MB_NoCache_MIG_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_auto_us_3 || ORIG_REF_NAME==MB_NoCache_MIG_auto_us_3} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_3/MB_NoCache_MIG_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_auto_ds_3 || ORIG_REF_NAME==MB_NoCache_MIG_auto_ds_3} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_4/MB_NoCache_MIG_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_auto_ds_4 || ORIG_REF_NAME==MB_NoCache_MIG_auto_ds_4} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_pc_1/MB_NoCache_MIG_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_auto_pc_1 || ORIG_REF_NAME==MB_NoCache_MIG_auto_pc_1} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_2/MB_NoCache_MIG_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_auto_us_2 || ORIG_REF_NAME==MB_NoCache_MIG_auto_us_2} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_5/MB_NoCache_MIG_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_auto_ds_5 || ORIG_REF_NAME==MB_NoCache_MIG_auto_ds_5} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_axi_periph_0/MB_NoCache_MIG_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_NoCache_MIG_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_axi_intc_0/MB_NoCache_MIG_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MB_NoCache_MIG_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_xlconcat_0/MB_NoCache_MIG_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MB_NoCache_MIG_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_mdm_1_0/MB_NoCache_MIG_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_mdm_1_0 || ORIG_REF_NAME==MB_NoCache_MIG_mdm_1_0} -quiet] -quiet

# IP: bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_rst_mig_7series_0_166M_1/MB_NoCache_MIG_rst_mig_7series_0_166M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_NoCache_MIG_rst_mig_7series_0_166M_1 || ORIG_REF_NAME==MB_NoCache_MIG_rst_mig_7series_0_166M_1} -quiet] -quiet

# XDC: bd/MB_NoCache_MIG/MB_NoCache_MIG_ooc.xdc
