# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Desktop/NeTV2_MIG/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/Desktop/NeTV2_MIG/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Desktop/NeTV2_MIG/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/hdl/MB_NoCache_MIG_wrapper.vhd
add_files D:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/MB_NoCache_MIG.bd
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_clk_wiz_0_0/MB_NoCache_MIG_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_clk_wiz_0_0/MB_NoCache_MIG_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_clk_wiz_0_0/MB_NoCache_MIG_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_mig_7series_0_1/MB_NoCache_MIG_mig_7series_0_1/user_design/constraints/MB_NoCache_MIG_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_mig_7series_0_1/MB_NoCache_MIG_mig_7series_0_1/user_design/constraints/MB_NoCache_MIG_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_axi_uartlite_0_0/MB_NoCache_MIG_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_axi_uartlite_0_0/MB_NoCache_MIG_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_axi_uartlite_0_0/MB_NoCache_MIG_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_0/MB_NoCache_MIG_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_0/MB_NoCache_MIG_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_0/MB_NoCache_MIG_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_v10_0/MB_NoCache_MIG_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_v10_0/MB_NoCache_MIG_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_ilmb_v10_0/MB_NoCache_MIG_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_ilmb_v10_0/MB_NoCache_MIG_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_dlmb_bram_if_cntlr_0/MB_NoCache_MIG_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_ilmb_bram_if_cntlr_0/MB_NoCache_MIG_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_lmb_bram_0/MB_NoCache_MIG_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_xbar_0/MB_NoCache_MIG_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_3/MB_NoCache_MIG_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_3/MB_NoCache_MIG_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_3/MB_NoCache_MIG_auto_us_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_3/MB_NoCache_MIG_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_3/MB_NoCache_MIG_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_3/MB_NoCache_MIG_auto_ds_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_4/MB_NoCache_MIG_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_4/MB_NoCache_MIG_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_4/MB_NoCache_MIG_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_pc_1/MB_NoCache_MIG_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_2/MB_NoCache_MIG_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_2/MB_NoCache_MIG_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_us_2/MB_NoCache_MIG_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_5/MB_NoCache_MIG_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_5/MB_NoCache_MIG_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_auto_ds_5/MB_NoCache_MIG_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_axi_intc_0/MB_NoCache_MIG_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_axi_intc_0/MB_NoCache_MIG_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_microblaze_0_axi_intc_0/MB_NoCache_MIG_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_mdm_1_0/MB_NoCache_MIG_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_mdm_1_0/MB_NoCache_MIG_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_mdm_1_0/MB_NoCache_MIG_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_rst_mig_7series_0_166M_1/MB_NoCache_MIG_rst_mig_7series_0_166M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_rst_mig_7series_0_166M_1/MB_NoCache_MIG_rst_mig_7series_0_166M_1.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/ip/MB_NoCache_MIG_rst_mig_7series_0_166M_1/MB_NoCache_MIG_rst_mig_7series_0_166M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Desktop/NeTV2_MIG/project_1/project_1.srcs/sources_1/bd/MB_NoCache_MIG/MB_NoCache_MIG_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktop/NeTV2_MIG/project_1/project_1.srcs/constrs_1/imports/project_2/NeTV2.xdc
set_property used_in_implementation false [get_files D:/Desktop/NeTV2_MIG/project_1/project_1.srcs/constrs_1/imports/project_2/NeTV2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MB_NoCache_MIG_wrapper -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MB_NoCache_MIG_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MB_NoCache_MIG_wrapper_utilization_synth.rpt -pb MB_NoCache_MIG_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
